[package]
name = "rustnake"
version = "1.2.0"
edition = "2021"

[dependencies]
crossterm = "0.28"
rand = "0.8"
serde = { version = "1.0", features = ["derive"] }
toml = "0.8"
unicode-width = "0.1"

[profile.release]
lto = "thin"
codegen-units = 1
strip = "symbols"
